// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surveillance.proto

package as.surveillance;

public interface accessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:surveillance.accessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
