// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surveillance.proto

package as.surveillance;

public interface accessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:surveillance.accessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();
}
