// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: surveillance.proto

package as.surveillance;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:surveillance.Empty)
    com.google.protobuf.MessageOrBuilder {
}
