// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package as.security;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.Empty)
    com.google.protobuf.MessageOrBuilder {
}
