// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package as.security;

public interface RequestBoardingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.RequestBoarding)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string flightId = 1;</code>
   */
  java.lang.String getFlightId();
  /**
   * <code>string flightId = 1;</code>
   */
  com.google.protobuf.ByteString
      getFlightIdBytes();
}
