// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package as.security;

public interface RequestClearanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.RequestClearance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 passportNo = 2;</code>
   */
  int getPassportNo();
}
