// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package as.security;

public interface ResponseDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.ResponseDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
