// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: security.proto

package as.security;

public interface ResponseClearanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:security.ResponseClearance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
