// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAccess.proto

package as.userAccess;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userAccess.Empty)
    com.google.protobuf.MessageOrBuilder {
}
