// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAccess.proto

package as.userAccess;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userAccess.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
